#' Write a printable PDF file.
#'
#' A utility to generate a PDF file ready for printing labels.
#'
#' This function generates a PDF document that can be printed directly to sheets
#' of labels/stickers for the easy and clear identification of experimental
#' samples. The default behaviour is to print the same ID across all labels in a
#' row, with a different ID for each row.
#'
#'
#' @param ids A character vector of IDs as generated by
#'   \code{\link[idLabelR]{make_ids}}.
#' @param layout A \code{\link{list}} object describing the layout of labels on
#'   the sheet to be printed. See Details to learn how to customise this.
#' @param printing An optional character to identify multiple copies of the same
#'   label sheet. Default is to ignore this feature.
#' @param byRow By default, IDs are repeated for all labels in a row. If
#'   \code{byRow = FALSE}, then IDs are repeated for all labels in a column.
#' @param file The name of the file to be written to. The default is
#'   \code{"Labels.pdf"} in the current working directory.
#' @param ... Additional parameters passed to \code{\link[grDevices]{pdf}}.
#'
#' @seealso \code{\link[idLabelR]{make_ids}}. Also see
#'   \code{\link[grDevices]{pdf}} for detail on additional PDF printing
#'   parameters.
#'
#' @examples
#' require(idLabelR)

#' example_spreadsheet = system.file("extdata", "Example.txt", package = "idLabelR")
#' ids = make_ids(file = example_spreadsheet)
#' layout = get_layout("cryobabies_LCRY_1700_A4")
#' make_pdf(ids, layout)
#'
#' # Additionally prints a timestamp and identifier
#' # to distinguish repeated printings of the same page.
#' make_pdf(ids, layout, printing = "a")
#'
#' # 17 rows of 5 labels for each ID.
#' make_pdf(ids, layout, byRow = TRUE, file = "Labels_by_row.pdf")
#' # 5 columns of 17 labels for each ID.
#' make_pdf(ids, layout, byRow = FALSE, file = "Labels_by_col.pdf")
#'
#' @importFrom grDevices pdf dev.off
#' @importFrom graphics par text
#' @importFrom tools file_path_sans_ext
#'
#' @export
make_pdf = function(ids, layout, byRow = TRUE, printing = NULL, file = "Labels.pdf", ...){
	if(layout$units == "mm"){
			layout$page.width = layout$page.width / 25.4
			layout$page.height = layout$page.height / 25.4
			layout$label.x = layout$label.x / 25.4
			layout$label.y = layout$label.y / 25.4
			layout$timestamp.x = layout$timestamp.x / 25.4
			layout$timestamp.y = layout$timestamp.y / 25.4
	}


	if(!is.null(printing)) printing = paste0("_", printing)

	split.vector = function(v, n){
	  ncols = floor(length(v)/n)
	  if(ncols > 0){
	  	return(c(split(v[1:(n * ncols)], rep(1:ncols, each=n)), list(v[(n * ncols + 1):length(v)])))
	  }else{
	  	return(list(v[(n * ncols + 1):length(v)]))
	  }
	}

	if(byRow){
		pages = split.vector(ids, n = length(layout$label.y))
		grDevices::pdf(file = paste0(tools::file_path_sans_ext(file), printing, ".pdf"), width = layout$page.width, height = layout$page.height)
		graphics::par(mar = c(0, 0, 0, 0))
		for(p in 1:length(pages)){
			n = 1
			plot(0, xlim=c(0, layout$page.width), ylim=c(layout$page.height, 0), ann=F, bty="n", type="n", xaxt = "n", yaxt = "n", xaxs = "i", yaxs = "i")
			for(y in layout$label.y){
				text = pages[[p]][n]
				for(x in layout$label.x){
					graphics::text(x, y, text, adj = c(0.5, 0.5), cex = 1, font = 2)
				}
				n = n + 1
			}
			# Add vertical date and sheet stamp.
			if(!is.null(printing) & !is.null(layout$timestamp.x) & !is.null(layout$timestamp.y) & !is.null(layout$timestamp.size)){
				graphics::text(layout$timestamp.x, layout$timestamp.y, paste0("Page  ", p, printing, "  ", Sys.Date()), adj = c(0, 0), cex = layout$timestamp.size, srt = -90)
			}
		}
	}else{
		pages = split.vector(ids, n = length(layout$label.x))
		grDevices::pdf(file = paste0(tools::file_path_sans_ext(file), printing, ".pdf"), width = layout$page.width, height = layout$page.height)
		graphics::par(mar = c(0, 0, 0, 0))
		for(p in 1:length(pages)){
			n = 1
			plot(0, xlim=c(0, layout$page.width), ylim=c(layout$page.height, 0), ann=F, bty="n", type="n", xaxt = "n", yaxt = "n", xaxs = "i", yaxs = "i")
			for(x in layout$label.x){
				text = pages[[p]][n]
				for(y in layout$label.y){
					graphics::text(x, y, text, adj = c(0.5, 0.5), cex = 1, font = 2)
				}
				n = n + 1
			}
			# Add vertical date and sheet stamp.
			if(!is.null(printing) & !is.null(layout$timestamp.x) & !is.null(layout$timestamp.y) & !is.null(layout$timestamp.size)){
				graphics::text(layout$timestamp.x, layout$timestamp.y, paste0("Page  ", p, printing, "  ", Sys.Date()), adj = c(0, 0), cex = layout$timestamp.size, srt = -90)
			}
		}
	}


	grDevices::dev.off()
}

##########

